const errorMassageMap = new Map();
errorMassageMap.set('4041', '找不到目标');
errorMassageMap.set('4001', '登陆方式失败');
errorMassageMap.set('4002', '该用户未注册或密码不正确');
errorMassageMap.set('4003', '这个用户已经被停权');
errorMassageMap.set('4004', '用户还没有登录');
errorMassageMap.set('4010', '登陆短信验证失败');
errorMassageMap.set('4011', '注册短信验证失败');
errorMassageMap.set('4012', '注册号码未验证或者不存在');
errorMassageMap.set('4013', '电话号码已经被注册');
errorMassageMap.set('4014', '找回密码验证失败');
errorMassageMap.set('4015', '微信短信验证失败');
errorMassageMap.set('4016', '找不到这个用户');
errorMassageMap.set('4031', '找不到商品');
